theme: minima
title: Victor's Website and Blog
author: Victor Choi
email: victor_choi@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  Welcome! My name is Victor Choi. 
  I do product analytics, and in this website I will write about related topics that I am interested in.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
